language: node_js
node_js:
- '12.13'

before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa

script:
- ssh -i deploy_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no jarvis@161.35.77.232 'cd /home/jarvis/jarvis/Jarvis_website && git pull origin main && npm install && npm run build && rm -rf /var/www/html/* && mv build/* /var/www/html/'

branches:
  only:
  - Travis
