# addons:
#   ssh_known_hosts: <deploy-host>

# before_deploy:
# - openssl aes-256-cbc -K $encrypted_<...>_key -iv $encrypted_<...>_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
# - eval "$(ssh-agent -s)"
# - chmod 600 /tmp/deploy_rsa
# - ssh-add /tmp/deploy_rsa

deploy:
  - provider: script
    skip_cleanup: true
    script: npm install
    on:
      branch: main
  - provider: script
    skip_cleanup: true
    script: npm run build
    on:
      branch: master