language: node_js
node_js:
- '12.13'

before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out deploy_rsa -d

script:
- cd /tmp
- ssh -i deploy_rsa jarvis@161.35.77.232 -y
- cd /home/jarvis/jarvis/Jarvis_website
- git pull origin main
- npm install
- npm run build
- rm -rf /var/www/html/*
- mv build/* /var/www/html

branches:
  only:
  - Travis
